# action.yml
name: 'ref-to-tag'
description: 'Get a docker-compatible tag from a Github ref'
inputs:
  ref:  # The input github ref
    description: 'your github.ref variable'
    required: true
  head_ref: The input head ref
    description: 'your github.head_ref variable'
    required: true
outputs:
  tag: 
    description: 'a Docker-compatible tag'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.ref }}
    - ${{ inputs.head_ref }}
